### ISSUE TITLE
Gameplay menu prints twice when hangman finishes.

### ISSUE THREAD

**Issue by scoopaldish** [scoopaldish/Culberson_Nix_Oliver_CSCI2270_FinalProject#2]
Nothing new, but I wanted to show you guys the issues thing. We can log what needs to be fixed and when on here.

**Comment by scoopaldish** [comment]
Someone should close this if it's all working properly. I would but I haven't compiled it.

**Comment by haydennix55** [comment]
Class Contribution fixed the bug...Bravoooo
